config/routes.rb
Rails.application.routes.draw do
  resources :climates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/climates_controller.rb
class ClimatesController < ApplicationController
  require 'net/http'

  before_action :set_climate, only: [:show, :edit, :update, :destroy]

  # GET /climates
  # GET /climates.json
  def index
    # @climates = Climate.all

  end

  # GET /climates/1
  # GET /climates/1.json
  def show
    uri = URI('https://api.sheety.co/8f5bb90a-3df4-4f5a-a41f-603a5000dfea')
    response = Net::HTTP.get(uri)
    @response = JSON.parse(response)
  end

  # GET /climates/new
  def new
    @climate = Climate.new
  end

  # GET /climates/1/edit
  def edit
  end

  # POST /climates
  # POST /climates.json
  def create
    @climate = Climate.new(climate_params)

    respond_to do |format|
      if @climate.save
        format.html { redirect_to @climate, notice: 'Climate was successfully created.' }
        format.json { render :show, status: :created, location: @climate }
      else
        format.html { render :new }
        format.json { render json: @climate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /climates/1
  # PATCH/PUT /climates/1.json
  def update
    respond_to do |format|
      if @climate.update(climate_params)
        format.html { redirect_to @climate, notice: 'Climate was successfully updated.' }
        format.json { render :show, status: :ok, location: @climate }
      else
        format.html { render :edit }
        format.json { render json: @climate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climates/1
  # DELETE /climates/1.json
  def destroy
    @climate.destroy
    respond_to do |format|
      format.html { redirect_to climates_url, notice: 'Climate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_climate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def climate_params
      params.fetch(:climate, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/climates_helper.rb
module ClimatesHelper
end

app/views/climates/_form.html.erb
<%= form_with(model: climate, local: true) do |form| %>
  <% if climate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(climate.errors.count, "error") %> prohibited this climate from being saved:</h2>

      <ul>
      <% climate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/climates/edit.html.erb
<h1>Editing Climate</h1>

<%= render 'form', climate: @climate %>

<%= link_to 'Show', @climate %> |
<%= link_to 'Back', climates_path %>

app/views/climates/index.html.erb
<%= pie_chart ({
  "Extremly Concerned" => 31,
  "Very Concerned" => 48,
  "Not Very Concerned" => 17,
  "Not at All Concerned" => 3
  }) %>

app/views/climates/new.html.erb
<h1>New Climate</h1>

<%= render 'form', climate: @climate %>

<%= link_to 'Back', climates_path %>

app/views/climates/show.html.erb
<% response = @response[0] %>
<button class="female"> Female </button>
<button class="male"> Male </button>
<button class="18-24"> 18-24 </button>
<button class="35-49"> 35-49 </button>
<button class="50-64"> 50-64 </button>
<button class="65"> 65+ </button>

<div id="total">
  <h1> Total </h1>
  <%= pie_chart ({
    "Extremly Concerned" => (response["ExtremelyConcerned"].to_i),
    "Very Concerned" => (response["VeryConcerned"].to_i),
    "Not Very Concerned" => (response["NotVeryConcerned"].to_i),
    "Not at All Concerned" => (response["NotAtAllConcerned"].to_i),
    "Don't Know" => (response["don’TKnow"].to_i)
    }) %>
</div>
<div id="female" class="hidden">
  <h1> Female </h1>
  <% response = @response[1] %>
  <%= pie_chart ({
    "Extremly Concerned" => (response["ExtremelyConcerned"].to_i),
    "Very Concerned" => (response["VeryConcerned"].to_i),
    "Not Very Concerned" => (response["NotVeryConcerned"].to_i),
    "Not at All Concerned" => (response["NotAtAllConcerned"].to_i),
    "Don't Know" => (response["don’TKnow"].to_i)
  }) %>
</div>
<div id="male" class="hidden">
  <h1> Male </h1>
  <% response = @response[2] %>
  <%= pie_chart ({
    "Extremly Concerned" => (response["ExtremelyConcerned"].to_i),
    "Very Concerned" => (response["VeryConcerned"].to_i),
    "Not Very Concerned" => (response["NotVeryConcerned"].to_i),
    "Not at All Concerned" => (response["NotAtAllConcerned"].to_i),
    "Don't Know" => (response["don’TKnow"].to_i)
    }) %>
</div>

<div id="18-24" class="hidden">
  <h1> 18-24 </h1>
  <% response = @response[3] %>
  <%= pie_chart ({
    "Extremly Concerned" => (response["ExtremelyConcerned"].to_i),
    "Very Concerned" => (response["VeryConcerned"].to_i),
    "Not Very Concerned" => (response["NotVeryConcerned"].to_i),
    "Not at All Concerned" => (response["NotAtAllConcerned"].to_i),
    "Don't Know" => (response["don’TKnow"].to_i)
    }) %>
</div>

<div id="35-49" class="hidden">
  <h1> 35-49 </h1>
  <% response = @response[4] %>
  <%= pie_chart ({
    "Extremly Concerned" => (response["ExtremelyConcerned"].to_i),
    "Very Concerned" => (response["VeryConcerned"].to_i),
    "Not Very Concerned" => (response["NotVeryConcerned"].to_i),
    "Not at All Concerned" => (response["NotAtAllConcerned"].to_i),
    "Don't Know" => (response["don’TKnow"].to_i)
    }) %>
</div>

<div id="50-64" class="hidden">
  <h1> 50-64 </h1>
  <% response = @response[5] %>
  <%= pie_chart ({
    "Extremly Concerned" => (response["ExtremelyConcerned"].to_i),
    "Very Concerned" => (response["VeryConcerned"].to_i),
    "Not Very Concerned" => (response["NotVeryConcerned"].to_i),
    "Not at All Concerned" => (response["NotAtAllConcerned"].to_i),
    "Don't Know" => (response["don’TKnow"].to_i)
    }) %>
</div>

<div id="65" class="hidden">
  <h1> 65+ </h1>
  <% response = @response[6] %>
  <%= pie_chart ({
    "Extremly Concerned" => (response["ExtremelyConcerned"].to_i),
    "Very Concerned" => (response["VeryConcerned"].to_i),
    "Not Very Concerned" => (response["NotVeryConcerned"].to_i),
    "Not at All Concerned" => (response["NotAtAllConcerned"].to_i),
    "Don't Know" => (response["don’TKnow"].to_i)
    }) %>
</div>

<script>
    $('.female').on('click', function(e) {
      $('#35-49, #18-24, #50-64, #65, #male, #total').hide();
      $('#female').show();
    });

    $('.male').on('click', function(e) {
      $('#35-49, #50-64, #65, #18-24, #female, #total').hide();
      $('#male').show();
    });

    $('.18-24').on('click', function(e) {
      $('#35-49, #50-64, #65, #male, #female, #total').hide();
      $('#18-24').show();
    });

    $('.35-49').on('click', function(e) {
      $('#18-24, #50-64, #65, #male, #female, #total').hide();
      $('#35-49').show();
    });

    $('.50-64').on('click', function(e) {
      $('#18-24, #35-49, #65, #male, #female, #total').hide();
      $('#50-64').show();
    });

    $('.65').on('click', function(e) {
      $('#18-24, #35-49, #50-64, #65, #male, #female, #total').hide();
      $('#65').show();
    });


</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClimateApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>